name: Publish Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tool
        run: uv sync --dev

      - name: Build package
        run: uv build

      #- name: Install Twine
      #  run: uv pip install twine

      - name: Publish package distributions to PyPI (twine)
        if: github.ref == 'refs/heads/main'
        run: uvx twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
